version: "3.1"
services:
  database:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb/db:/docker-entrypoint-initdb.d/
      - ./mariadb/data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=iamgroot"